### ISSUE TITLE
Material illustration is broken.

### ISSUE THREAD

**Issue by josiah-wolf-oberholtzer** [Abjad/ide#80]
AbjadIDE doesn't create `__illustrate__.py` files for material packages like it does for segment packages, but still expects to find `__illustrate__.py` files in order to create LilyPond/PDF output for material packages.

**Comment by trevorbaca** [comment]
Call (illm) to create the __illustrate__.py file.

Note that material packages are created without an __illustrate__.py file because many material packages won't need illustration.

Note, too, that there's no one-size-fits-all type of illustration for materials. So the __illustrate__.py file created by (illm) should be freely adjusted by a couple of lines to match the material being illustrated.
