### ISSUE TITLE
Extend (pdfm) to clear terminal at start of run

### ISSUE THREAD

**Issue by trevorbaca** [Abjad/ide#83]

**Comment by trevorbaca** [comment]
Also extend (pdfm) to *rename* illustration.ly and illustration.pdf to illustration.ly.old and illustration.pdf.old at the beginning of a run.

This is better than removing illustration.ly and illustration.pdf at the beginning of a run. Because sometimes a run fails to produce output. In which case the old output should be restored.

**Comment by josiah-wolf-oberholtzer** [comment]
:+1: And we need a thorough battery of *failure* tests, as there are many ways (pdfm) can go wrong.

**Comment by trevorbaca** [comment]
Yeah, that's really true.

**Comment by josiah-wolf-oberholtzer** [comment]
A thought about failure handling (which I will move to another issue properly): We can use `sys.exit(...)` to emit exit codes in the illustration / ly-making / pdf-making files. Rather than simply emitting 0 for success and 1 for failure, we can use an enumeration object (Python's IntEnum) to declare a set of distinct kinds of failure as integer flags to be passed to `sys.exit(...)`:

- failed to import `definition.py`
- failed to create a LilyPondFile object
- failed to write the LilyPondFile to disk
- failed to find the `lilypond` executable
- failed to run LilyPond against the illustration ly

The enum can be importable both by the illustration boilerplate scripts and by the IDE itself, allowing for proper comparison of exit codes without code duplication. Using such as regime could let us improve how we handle failures within the IDE by providing more specific messaging (among other things).

E.g.:

```
...
if not os.path.exits(illustration_ly_path):
    exit_code = ExitCodes.ILLUSTRATION_LY_NOT_FOUND
    sys.exit(exit_code)
...
```

Systems programming is tough, so there's no reason not to use the shell affordances available to us. And enumerations (supported in both Py 2 (via backports) and 3 (natively)) will make it simple and literate.

**Comment by trevorbaca** [comment]
:+1:

Great idea.
